name: Docker Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          dockerfile: Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cicd_automated:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cicd_automated:latest

      - name: RunTests
        run: go test -v ./...
        
      - name: Scan Docker Image for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bevice1/cicd_automated:latest
          format: table
          vuln-type: 'os,library'
          exit-code: "1"

